<a href="https://colab.research.google.com/github/gaboitec/Challenge-TelcomX-ONE-pandas-matplotlib/blob/main/TelecomX_LATAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#📌 Extracción

In [1]:
import pandas as pd

In [2]:
datos = pd.read_json('TelecomX_Data.json')

In [3]:
datos.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

#🔧 Transformación

In [4]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

In [5]:
datos['customer'].head()

0    {'gender': 'Female', 'SeniorCitizen': 0, 'Part...
1    {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...
2    {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...
3    {'gender': 'Male', 'SeniorCitizen': 1, 'Partne...
4    {'gender': 'Female', 'SeniorCitizen': 1, 'Part...
Name: customer, dtype: object

In [6]:
df_normalizado = pd.json_normalize(datos['account'])
df_normalizado.head()

,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,One year,Yes,Mailed check,65.6,593.3
1,Month-to-month,No,Mailed check,59.9,542.4
2,Month-to-month,Yes,Electronic check,73.9,280.85
3,Month-to-month,Yes,Electronic check,98.0,1237.85
4,Month-to-month,Yes,Mailed check,83.9,267.4

In [7]:
df_datos = pd.json_normalize(datos.to_dict(orient='records'))
df_datos.head()

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [8]:
df_datos = df_datos.drop(labels=['customerID', 'account.Charges.Total'], axis=1, inplace=False)

In [9]:
df_datos

,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,internet.OnlineSecurity,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly
0,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60
1,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90
2,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90
3,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00
4,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,No,Female,0,No,No,13,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check,55.15
7263,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10
7264,No,Male,0,No,No,2,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30
7265,No,Male,0,Yes,Yes,67,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85
7266,No,Male,0,Yes,Yes,63,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00

In [10]:
df_datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Churn                      7267 non-null   object
 1   customer.gender            7267 non-null   object
 2   customer.SeniorCitizen     7267 non-null   int64
 3   customer.Partner           7267 non-null   object
 4   customer.Dependents        7267 non-null   object
 5   customer.tenure            7267 non-null   int64
 6   phone.PhoneService         7267 non-null   object
 7   phone.MultipleLines        7267 non-null   object
 8   internet.InternetService   7267 non-null   object
 9   internet.OnlineSecurity    7267 non-null   object
 10  internet.OnlineBackup      7267 non-null   object
 11  internet.DeviceProtection  7267 non-null   object
 12  internet.TechSupport       7267 non-null   object
 13  internet.StreamingTV       7267 non-null   object
 14  internet.StreamingMovies   7267 non-null   object
 15  account.Contract           7267 non-null   object
 16  account.PaperlessBilling   7267 non-null   object
 17  account.PaymentMethod      7267 non-null   object
 18  account.Charges.Monthly    7267 non-null   float64
dtypes: float64(1), int64(2), object(16)
memory usage: 1.1+ MB

In [11]:
df_datos.duplicated().sum()

np.int64(27)

In [12]:
df_datos = df_datos.drop_duplicates()

In [13]:
df_datos.duplicated().sum()

np.int64(0)

In [14]:
df_datos.isnull().sum()

Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
dtype: int64

In [15]:
import numpy as np

df_datos['customer.SeniorCitizen'] = df_datos['customer.SeniorCitizen'].astype(np.int64)

/tmp/ipykernel_561/2058098495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos['customer.SeniorCitizen'] = df_datos['customer.SeniorCitizen'].astype(np.int64)

In [16]:
df_datos['customer.tenure'] = df_datos['customer.tenure'].astype(np.int64)

/tmp/ipykernel_561/1926120638.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos['customer.tenure'] = df_datos['customer.tenure'].astype(np.int64)

In [17]:
df_datos

,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,internet.OnlineSecurity,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly
0,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60
1,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90
2,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90
3,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00
4,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,No,Female,0,No,No,13,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check,55.15
7263,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10
7264,No,Male,0,No,No,2,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30
7265,No,Male,0,Yes,Yes,67,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85
7266,No,Male,0,Yes,Yes,63,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00

In [18]:
df_datos['account.Charges.Monthly'] = df_datos['account.Charges.Monthly'].astype(np.float64)
df_datos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7240 entries, 0 to 7266
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Churn                      7240 non-null   object
 1   customer.gender            7240 non-null   object
 2   customer.SeniorCitizen     7240 non-null   int64
 3   customer.Partner           7240 non-null   object
 4   customer.Dependents        7240 non-null   object
 5   customer.tenure            7240 non-null   int64
 6   phone.PhoneService         7240 non-null   object
 7   phone.MultipleLines        7240 non-null   object
 8   internet.InternetService   7240 non-null   object
 9   internet.OnlineSecurity    7240 non-null   object
 10  internet.OnlineBackup      7240 non-null   object
 11  internet.DeviceProtection  7240 non-null   object
 12  internet.TechSupport       7240 non-null   object
 13  internet.StreamingTV       7240 non-null   object
 14  internet.StreamingMovies   7240 non-null   object
 15  account.Contract           7240 non-null   object
 16  account.PaperlessBilling   7240 non-null   object
 17  account.PaymentMethod      7240 non-null   object
 18  account.Charges.Monthly    7240 non-null   float64
dtypes: float64(1), int64(2), object(16)
memory usage: 1.1+ MB

/tmp/ipykernel_561/2142374927.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos['account.Charges.Monthly'] = df_datos['account.Charges.Monthly'].astype(np.float64)

In [19]:
df_datos['account.Contract']

0             One year
1       Month-to-month
2       Month-to-month
3       Month-to-month
4       Month-to-month
             ...
7262          One year
7263    Month-to-month
7264    Month-to-month
7265          Two year
7266          Two year
Name: account.Contract, Length: 7240, dtype: object

In [20]:
df_datos['cuentas_diarias'] = (df_datos['account.Charges.Monthly'] * 12) / 365
df_datos

/tmp/ipykernel_561/418097354.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos['cuentas_diarias'] = (df_datos['account.Charges.Monthly'] * 12) / 365

,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,internet.OnlineSecurity,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,cuentas_diarias
0,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,2.156712
1,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,1.969315
2,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,2.429589
3,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,3.221918
4,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,2.758356
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,No,Female,0,No,No,13,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check,55.15,1.813151
7263,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,2.797808
7264,No,Male,0,No,No,2,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,1.653699
7265,No,Male,0,Yes,Yes,67,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,2.230685
7266,No,Male,0,Yes,Yes,63,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,1.939726

In [21]:
df_datos.columns = df_datos.columns.str.lower().str.replace('.', '_')
df_datos

,churn,customer_gender,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,phone_multiplelines,internet_internetservice,internet_onlinesecurity,internet_onlinebackup,internet_deviceprotection,internet_techsupport,internet_streamingtv,internet_streamingmovies,account_contract,account_paperlessbilling,account_paymentmethod,account_charges_monthly,cuentas_diarias
0,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,2.156712
1,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,1.969315
2,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,2.429589
3,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,3.221918
4,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,2.758356
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,No,Female,0,No,No,13,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check,55.15,1.813151
7263,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,2.797808
7264,No,Male,0,No,No,2,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,1.653699
7265,No,Male,0,Yes,Yes,67,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,2.230685
7266,No,Male,0,Yes,Yes,63,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,1.939726

In [22]:
cols_bol = ['churn', 'customer_partner', 'customer_dependents', 'phone_phoneservice', 'phone_multiplelines', 'internet_onlinesecurity', 'internet_onlinebackup', 'internet_deviceprotection', 'internet_techsupport', 'internet_streamingtv', 'internet_streamingmovies', 'account_paperlessbilling']
df_datos[cols_bol] = df_datos[cols_bol].replace({"Yes":1, "No":0, "No phone service":0, "No internet service":0})
df_datos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7240 entries, 0 to 7266
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   churn                      7240 non-null   object
 1   customer_gender            7240 non-null   object
 2   customer_seniorcitizen     7240 non-null   int64
 3   customer_partner           7240 non-null   int64
 4   customer_dependents        7240 non-null   int64
 5   customer_tenure            7240 non-null   int64
 6   phone_phoneservice         7240 non-null   int64
 7   phone_multiplelines        7240 non-null   int64
 8   internet_internetservice   7240 non-null   object
 9   internet_onlinesecurity    7240 non-null   int64
 10  internet_onlinebackup      7240 non-null   int64
 11  internet_deviceprotection  7240 non-null   int64
 12  internet_techsupport       7240 non-null   int64
 13  internet_streamingtv       7240 non-null   int64
 14  internet_streamingmovies   7240 non-null   int64
 15  account_contract           7240 non-null   object
 16  account_paperlessbilling   7240 non-null   int64
 17  account_paymentmethod      7240 non-null   object
 18  account_charges_monthly    7240 non-null   float64
 19  cuentas_diarias            7240 non-null   float64
dtypes: float64(2), int64(13), object(5)
memory usage: 1.2+ MB

/tmp/ipykernel_561/289730319.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_datos[cols_bol] = df_datos[cols_bol].replace({"Yes":1, "No":0, "No phone service":0, "No internet service":0})
/tmp/ipykernel_561/289730319.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos[cols_bol] = df_datos[cols_bol].replace({"Yes":1, "No":0, "No phone service":0, "No internet service":0})

In [23]:
df_datos['churn'] = df_datos['churn'].replace({"":None})
df_datos = df_datos.dropna()
df_datos.groupby('churn').count()

/tmp/ipykernel_561/1244733081.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos['churn'] = df_datos['churn'].replace({"":None})

,customer_gender,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,phone_multiplelines,internet_internetservice,internet_onlinesecurity,internet_onlinebackup,internet_deviceprotection,internet_techsupport,internet_streamingtv,internet_streamingmovies,account_contract,account_paperlessbilling,account_paymentmethod,account_charges_monthly,cuentas_diarias
churn,,,,,,,,,,,,,,,,,,,
0,5159,5159,5159,5159,5159,5159,5159,5159,5159,5159,5159,5159,5159,5159,5159,5159,5159,5159,5159
1,1857,1857,1857,1857,1857,1857,1857,1857,1857,1857,1857,1857,1857,1857,1857,1857,1857,1857,1857

In [24]:
df_datos['churn'] = df_datos['churn'].astype(np.int64)
df_datos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7016 entries, 0 to 7266
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   churn                      7016 non-null   int64
 1   customer_gender            7016 non-null   object
 2   customer_seniorcitizen     7016 non-null   int64
 3   customer_partner           7016 non-null   int64
 4   customer_dependents        7016 non-null   int64
 5   customer_tenure            7016 non-null   int64
 6   phone_phoneservice         7016 non-null   int64
 7   phone_multiplelines        7016 non-null   int64
 8   internet_internetservice   7016 non-null   object
 9   internet_onlinesecurity    7016 non-null   int64
 10  internet_onlinebackup      7016 non-null   int64
 11  internet_deviceprotection  7016 non-null   int64
 12  internet_techsupport       7016 non-null   int64
 13  internet_streamingtv       7016 non-null   int64
 14  internet_streamingmovies   7016 non-null   int64
 15  account_contract           7016 non-null   object
 16  account_paperlessbilling   7016 non-null   int64
 17  account_paymentmethod      7016 non-null   object
 18  account_charges_monthly    7016 non-null   float64
 19  cuentas_diarias            7016 non-null   float64
dtypes: float64(2), int64(14), object(4)
memory usage: 1.1+ MB

/tmp/ipykernel_561/3679917758.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos['churn'] = df_datos['churn'].astype(np.int64)

In [25]:
df_datos['customer_gender'].value_counts()

customer_gender
Male      3537
Female    3479
Name: count, dtype: int64

In [26]:
df_datos['internet_internetservice'].value_counts()

internet_internetservice
Fiber optic    3089
DSL            2419
No             1508
Name: count, dtype: int64

In [27]:
df_datos['account_contract'].value_counts()

account_contract
Month-to-month    3851
Two year          1692
One year          1473
Name: count, dtype: int64

In [28]:
df_datos['account_paymentmethod'].value_counts()

account_paymentmethod
Electronic check             2359
Mailed check                 1593
Bank transfer (automatic)    1544
Credit card (automatic)      1520
Name: count, dtype: int64

In [29]:
df_datos.sample(10)

,churn,customer_gender,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,phone_multiplelines,internet_internetservice,internet_onlinesecurity,internet_onlinebackup,internet_deviceprotection,internet_techsupport,internet_streamingtv,internet_streamingmovies,account_contract,account_paperlessbilling,account_paymentmethod,account_charges_monthly,cuentas_diarias
3890,0,Female,0,1,1,58,1,1,DSL,1,0,1,1,1,0,Two year,0,Mailed check,75.80,2.492055
2628,0,Female,0,0,0,54,1,0,No,0,0,0,0,0,0,Two year,1,Mailed check,20.50,0.673973
3667,0,Female,0,1,1,67,1,1,Fiber optic,1,0,0,1,1,1,Two year,0,Credit card (automatic),106.70,3.507945
5163,0,Female,0,1,0,46,1,1,Fiber optic,0,1,0,1,1,1,One year,1,Electronic check,103.15,3.391233
2611,0,Female,0,0,0,61,1,1,Fiber optic,1,1,1,1,1,1,One year,1,Mailed check,115.10,3.784110
6283,1,Female,0,1,0,2,1,0,Fiber optic,0,1,1,0,0,0,Month-to-month,0,Bank transfer (automatic),79.70,2.620274
7147,0,Male,0,1,1,58,0,0,DSL,1,1,1,0,1,0,One year,0,Mailed check,50.00,1.643836
6646,0,Male,0,1,0,69,1,0,DSL,1,1,1,1,1,1,Two year,1,Mailed check,84.70,2.784658
3615,0,Female,0,0,0,2,1,0,No,0,0,0,0,0,0,Month-to-month,1,Mailed check,20.00,0.657534
1653,0,Male,0,1,0,42,1,1,Fiber optic,1,0,1,0,0,1,Month-to-month,1,Electronic check,94.40,3.103562

In [30]:
df_datos['account_contract'] = df_datos['account_contract'].replace('[^a-zA-Z0-9]', ' ', regex=True)
df_datos['account_paymentmethod'] = df_datos['account_paymentmethod'].replace('[^a-zA-Z0-9]', ' ', regex=True)

/tmp/ipykernel_561/3881517981.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos['account_contract'] = df_datos['account_contract'].replace('[^a-zA-Z0-9]', ' ', regex=True)
/tmp/ipykernel_561/3881517981.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos['account_paymentmethod'] = df_datos['account_paymentmethod'].replace('[^a-zA-Z0-9]', ' ', regex=True)

In [31]:
df_datos.sample(10)

,churn,customer_gender,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,phone_multiplelines,internet_internetservice,internet_onlinesecurity,internet_onlinebackup,internet_deviceprotection,internet_techsupport,internet_streamingtv,internet_streamingmovies,account_contract,account_paperlessbilling,account_paymentmethod,account_charges_monthly,cuentas_diarias
3731,0,Female,0,1,0,59,1,1,Fiber optic,1,1,1,0,1,1,One year,1,Credit card automatic,109.15,3.588493
536,0,Male,0,0,0,46,0,0,DSL,0,0,1,1,0,0,One year,0,Credit card automatic,33.70,1.107945
5017,0,Male,1,0,0,9,1,1,Fiber optic,0,0,0,0,0,0,Month to month,1,Electronic check,74.05,2.434521
6628,0,Female,0,0,0,69,1,0,DSL,1,0,1,1,1,1,Two year,1,Credit card automatic,82.45,2.710685
1276,0,Female,0,0,0,70,0,0,DSL,1,0,1,1,1,1,Two year,1,Bank transfer automatic,58.35,1.918356
3869,0,Female,0,1,0,63,1,0,Fiber optic,1,0,1,0,0,0,One year,1,Credit card automatic,81.15,2.667945
6431,1,Female,0,1,0,2,1,0,Fiber optic,0,0,0,0,0,0,Month to month,1,Electronic check,70.70,2.324384
5318,0,Male,0,1,1,11,1,0,No,0,0,0,0,0,0,Month to month,1,Electronic check,20.45,0.672329
4292,0,Male,0,0,0,31,1,0,Fiber optic,0,1,0,0,1,1,Month to month,1,Electronic check,94.50,3.106849
4991,0,Male,0,1,1,12,1,0,No,0,0,0,0,0,0,Two year,0,Bank transfer automatic,21.05,0.692055

In [32]:
for col in ['customer_gender', 'internet_internetservice', 'account_contract', 'account_paymentmethod']:
    df_datos[col] = df_datos[col].astype(str).str.strip()
df_datos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7016 entries, 0 to 7266
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   churn                      7016 non-null   int64
 1   customer_gender            7016 non-null   object
 2   customer_seniorcitizen     7016 non-null   int64
 3   customer_partner           7016 non-null   int64
 4   customer_dependents        7016 non-null   int64
 5   customer_tenure            7016 non-null   int64
 6   phone_phoneservice         7016 non-null   int64
 7   phone_multiplelines        7016 non-null   int64
 8   internet_internetservice   7016 non-null   object
 9   internet_onlinesecurity    7016 non-null   int64
 10  internet_onlinebackup      7016 non-null   int64
 11  internet_deviceprotection  7016 non-null   int64
 12  internet_techsupport       7016 non-null   int64
 13  internet_streamingtv       7016 non-null   int64
 14  internet_streamingmovies   7016 non-null   int64
 15  account_contract           7016 non-null   object
 16  account_paperlessbilling   7016 non-null   int64
 17  account_paymentmethod      7016 non-null   object
 18  account_charges_monthly    7016 non-null   float64
 19  cuentas_diarias            7016 non-null   float64
dtypes: float64(2), int64(14), object(4)
memory usage: 1.1+ MB

/tmp/ipykernel_561/3948116685.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos[col] = df_datos[col].astype(str).str.strip()
/tmp/ipykernel_561/3948116685.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos[col] = df_datos[col].astype(str).str.strip()
/tmp/ipykernel_561/3948116685.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos[col] = df_datos[col].astype(str).str.strip()
/tmp/ipykernel_561/3948116685.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos[col] = df_datos[col].astype(str).str.strip()

In [33]:
# Convert specified object columns to pandas StringDtype
for col in ['customer_gender', 'internet_internetservice', 'account_contract', 'account_paymentmethod']:
    df_datos[col] = df_datos[col].astype(pd.StringDtype())

# Display the info again to see the updated dtypes
df_datos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7016 entries, 0 to 7266
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   churn                      7016 non-null   int64
 1   customer_gender            7016 non-null   string
 2   customer_seniorcitizen     7016 non-null   int64
 3   customer_partner           7016 non-null   int64
 4   customer_dependents        7016 non-null   int64
 5   customer_tenure            7016 non-null   int64
 6   phone_phoneservice         7016 non-null   int64
 7   phone_multiplelines        7016 non-null   int64
 8   internet_internetservice   7016 non-null   string
 9   internet_onlinesecurity    7016 non-null   int64
 10  internet_onlinebackup      7016 non-null   int64
 11  internet_deviceprotection  7016 non-null   int64
 12  internet_techsupport       7016 non-null   int64
 13  internet_streamingtv       7016 non-null   int64
 14  internet_streamingmovies   7016 non-null   int64
 15  account_contract           7016 non-null   string
 16  account_paperlessbilling   7016 non-null   int64
 17  account_paymentmethod      7016 non-null   string
 18  account_charges_monthly    7016 non-null   float64
 19  cuentas_diarias            7016 non-null   float64
dtypes: float64(2), int64(14), string(4)
memory usage: 1.1 MB

/tmp/ipykernel_561/3501187474.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_datos[col] = df_datos[col].astype(pd.StringDtype())

#📊 Carga y análisis

In [36]:
df_datos.describe()

,churn,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,phone_multiplelines,internet_onlinesecurity,internet_onlinebackup,internet_deviceprotection,internet_techsupport,internet_streamingtv,internet_streamingmovies,account_paperlessbilling,account_charges_monthly,cuentas_diarias
count,7016.000000,7016.000000,7016.000000,7016.000000,7016.000000,7016.000000,7016.000000,7016.000000,7016.000000,7016.000000,7016.000000,7016.000000,7016.000000,7016.000000,7016.000000,7016.000000
mean,0.264681,0.162628,0.484464,0.300599,32.462087,0.902794,0.423176,0.287628,0.346066,0.345068,0.291192,0.385690,0.389253,0.592930,64.869897,2.132709
std,0.441194,0.369052,0.499794,0.458551,24.526687,0.296260,0.494098,0.452689,0.475748,0.475424,0.454344,0.486793,0.487616,0.491323,30.055654,0.988131
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.250000,0.600000
25%,0.000000,0.000000,0.000000,0.000000,9.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.750000,1.175342
50%,0.000000,0.000000,0.000000,0.000000,29.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,70.400000,2.314521
75%,1.000000,0.000000,1.000000,1.000000,55.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,89.900000,2.955616
max,1.000000,1.000000,1.000000,1.000000,72.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,118.750000,3.904110

#📄Informe final